### ISSUE TITLE
String IDs not supported?

### ISSUE THREAD

**Issue by jbrassard** [joaonuno/flat-to-nested-js#10]
Hi,

I'm trying to nest a flat list with strings as IDs and Parents but the returned nested structure stays flat.
Looking at your test.js file, I see that only int are tested. Do you think strings should work?

Thanks!

**Comment by joaonuno** [comment]
I think it works. Is this what you want? http://requirebin.com/?gist=48c75716f18215ebeaaf74ff6c76842d

**Comment by jbrassard** [comment]
You are right, it works and even if I replace the Ids in your gist with string guids, it works.


It must be my code then, I'll continue looking.


Thanks!

________________________________
