### ISSUE TITLE
Could you provide information about nesting level on each node?

### ISSUE THREAD

**Issue by klaky** [joaonuno/flat-to-nested-js#14]
Could you provide information about nesting level on each node?

**Comment by nkgokul** [comment]
Are you looking for a summary like how many nested nodes are present within a node? Since recursive functions are used I think we can use a numberOfChildren at each level which will be the sum of the numberOfChildren fields of its children.

**Comment by joaonuno** [comment]
I think this SO post is related: https://stackoverflow.com/questions/50877234/treemodel-js-how-to-get-nest-level-while-walking-the-tree/50877473
