### ISSUE TITLE
Child node are not deleted from root

### ISSUE THREAD

**Issue by cybercandyman** [joaonuno/flat-to-nested-js#2]
With the example :
    flat = [
    {idchapter: 111, idparent: 11},
    {idchapter: 11, idparent: 1},
    {idchapter: 12, idparent: 1},
    {idchapter: 1}
    ];
child nodes are appended to their parents but are not deleted from the root 
http://jsfiddle.net/4zmbp8tL/

**Comment by joaonuno** [comment]
Hi,

You should instead try:

```js
var nested = flatToNested.convert(flat); 
console.log(nested);
```

The `nested` is the result of the conversion. The `flat ` is left in an unspecified state after the conversion. If you need the flat as it was before the conversion, you'll need to deep clone it before converting it.
