### ISSUE TITLE
my key result must have double quote

### ISSUE THREAD

**Issue by hahamed** [joaonuno/flat-to-nested-js#3]
Hello
Howto my key result must have double quote?
 {id: 1, text: "hamed" , ... }
be:
 {"id": 1, "text": "hamed" , ... }

thanks

**Comment by joaonuno** [comment]
The issue you're reporting doesn't seem to be related with this library. An object key is always a string and only needs the double quotes when exported as JSON.

Try calling `JSON.stringify` on the return value... it's hard to help you with the info you gave.

```
var nested = flatToNested.convert(flat);
console.log(JSON.stringify(nested));
```

**Comment by hahamed** [comment]
thanks
