### ISSUE TITLE
How do I get this?

### ISSUE THREAD

**Issue by maeishoj** [joaonuno/flat-to-nested-js#4]
Hey there, 

Just like for your tree-model-js, I want to use this library, but how do I get the actual js and min.js file? 
Sorry if the question seems stupidly easy, but I just don't get it... 

Would appreciate if you could let me know!

PS: Forgot to mention in javascript client side (im using angularjs).

Thanks!

**Comment by joaonuno** [comment]
Hi,

I haven't yet created a page to download browser-ready bundles but you can generate them yourself if you have git and node installed:

1) Clone the project `git clone https://github.com/joaonuno/flat-to-nested-js.git` and `cd` into the project folder
2) Run `npm install`
3) Run `npm run dist` to generate the bundles to the `dist` folder
