### ISSUE TITLE
Q: tree-model integration ?

### ISSUE THREAD

**Issue by X-Raym** [joaonuno/flat-to-nested-js#9]
Hi !

Can your [tree-model](https://www.npmjs.com/package/tree-model) npm package works with array converted with flat-to-nested ?  
If yes... how ? :)

Thanks for your answer :)

**Comment by joaonuno** [comment]
Hi, check if this [answer](https://stackoverflow.com/questions/41463575/integrating-jstree-with-treemodel/41471288#41471288) helps you. The relevant line is `root = tree.parse(flatToNested.convert(items))`.

**Comment by X-Raym** [comment]
@joaonuno thank you very much for your quick answe (and your scripts) !
Ok so it is one single line of code. Nice 👍
